### ISSUE TITLE
`Missing field $site_description$ in context for item archive.html` in CleanMagic

### ISSUE THREAD

**Issue by Cutuchiqueno** [katychuang/hakyll-cssgarden#4]
I am pretty new to hakyll and therefor do not fully understand the dimension of the error. Thus I am also not capable to solve it on my own.

A fresh install of the CleanMagic theme outputs:

```
[ERROR] Missing field $site_description$ in context for item archive.html
```

the same for `about.md`

**Comment by katychuang** [comment]
May I ask what the fields look like for each post as well as your site.hs file? It looks like the template is asking for the site_description field, which is defined in the example site.hs under the [siteCtx](https://github.com/katychuang/hakyll-cssgarden/blob/master/cleanMagic-hakyll/site.hs#L70) function

**Comment by katychuang** [comment]
In case I wasn't clear - the default hakyll installation of site.hs might look different than the one specifically for the CleanMagic theme template layout pages. 

Alternatively to the solution mentioned above, you can also remove from the html files any instance of `$site_description$`

**Comment by boredstiff** [comment]
Hi Katy,
I'm having the same problem as the original poster, but it seems to be for all variables defined in the site.hs SiteCtx, whether it's baseurl or site_description - I can get rid of these problems by just subbing them out in the source code, but I didn't know if there was something better I can be doing so that I can actually utilize the siteCtx strings. 

Thanks!

**Comment by katychuang** [comment]
The siteCtx strings like baseurl and site_description were hardcoded in to reduce rewriting them in the template files... so if you don't need them in the template files you don't need the strings inside siteCtx :)
